### ISSUE TITLE
[Bug] an error occur when there is a standalone note.

### ISSUE THREAD

**Issue by zyx335588** [frianasoa/Ze-Notes#1]
When there is a standalone note in the selected collection, an alert would occur.
![Snipaste_2023-02-03_17-04-38](https://user-images.githubusercontent.com/22871049/216557884-bdb322f0-a2fd-4409-b633-dd99209d1fa0.png)
Is it possible to ignore standalone notes in the collection?

**Comment by frianasoa** [comment]
Thank you for your feedback. 
Fixed in version 0.3.2. Please update.
