### ISSUE TITLE
Can you display pictures normally?

### ISSUE THREAD

**Issue by kmxj2020** [frianasoa/Ze-Notes#10]
The picture here can't be displayed normally. If it can't be displayed normally, can you use a symbol to indicate that there is a picture here? Otherwise, the picture can not be displayed, and it occupies a large display area. 
The problem is shown in the following figure 
<img width="774" alt="Snipaste_2023-12-04_20-02-48" src="https://github.com/frianasoa/Ze-Notes/assets/87763851/6a87a490-b5c3-44bc-9389-2b6246c9519a">

**Comment by frianasoa** [comment]
Hi!

Please check the latest version.

You could also filter out all images. The setting below will replace all pictures with [image].

![image](https://github.com/frianasoa/Ze-Notes/assets/5507310/c435fa3e-2b33-4075-a0d9-3f862ce524f8)
