### ISSUE TITLE
What is the tag "other"

### ISSUE THREAD

**Issue by wuyan0808** [frianasoa/Ze-Notes#12]
<img width="238" alt="PixPin_2023-12-15_18-48-14" src="https://github.com/frianasoa/Ze-Notes/assets/118701894/42496e6e-8b2d-4398-81a9-069f0707c10b">
This tag exists in some collections, does not exist in some collections,but i don't have this tag.

**Comment by frianasoa** [comment]
You will find this tag when you have untagged notes or annotations in your collection. However, it does not seem to show any content in the table for now. I have fixed that. 
I have changed "Other" into "Untagged". It was indeed misleading. Thanks for pointing out.
Please update the plugin and restart Zotero.

**Comment by wuyan0808** [comment]
<img width="342" alt="have notes" src="https://github.com/frianasoa/Ze-Notes/assets/118701894/62d5afc3-3612-4b5a-857a-d366b2f07441">

<img width="292" alt="no notes" src="https://github.com/frianasoa/Ze-Notes/assets/118701894/d873b511-efe3-4d98-876a-67e719986821">

Thank you for your answer,  it fits my guess. However, there seems to be a bug at present. If the PDF file in the a collection only has annotations and no notes exist, it does not appear to display Untagged tag in Ze Notes settings. If a note exists in the collection, Untagged tag will be displayed. Maybe, this is the logic of your design.

**Comment by frianasoa** [comment]
Hi!
Thanks. I have fixed the bug with pdf annotations.

**Comment by wuyan0808** [comment]
Thank you so much for your update.
