### ISSUE TITLE
Unable to display Chinese author name.

### ISSUE THREAD

**Issue by panyuz** [frianasoa/Ze-Notes#14]
Thank you for creating this incredibly useful plugin. I want to express my gratitude. However, I have come across a bug where author names are displayed correctly for English documents, but not for Chinese ones. I would appreciate it if you could let me know what additional information is needed to address this issue.

<img width="1625" alt="截屏2024-01-04 20 59 25" src="https://github.com/frianasoa/Ze-Notes/assets/4372695/4234f3d6-dc5b-404d-8b2d-e402bc227536">

**Comment by frianasoa** [comment]
Hi!
This is just a convenience column I created without thinking much about localization, so even if it works, you will end up with something like "季 et al. (2023)". "et al." is likely localized to your Zotero language, not the item's language. 
For now, try to update the plugin and see if it changes from "undefined et al. (2023)" to something else. 
If it does not change, please screenshot the results and if possible, also your Zotero entry. I would like to check the type of entry and the authors.

**Comment by panyuz** [comment]
Thank you for the update. Now the Chinese author names are displaying correctly. However, during the process of upgrading the plugin to version 0.76, Zotero crashes. Please refer to the video below for demonstration.

## 1  Chinese author names are displaying correctly
![Uploading 截屏2024-01-05 08.32.50.png…]()

##2 zotero crashes

https://github.com/frianasoa/Ze-Notes/assets/4372695/ef549cf4-c242-454a-9eb6-6d1796d5a010

[zotero crash.txt](https://github.com/frianasoa/Ze-Notes/files/13836758/zotero.crash.txt)

**Comment by frianasoa** [comment]
Thanks for your feedback.

* It displays "and" and "et al." in the language set in Zotero as expected. I am keeping these settings in the column "Source" for now. 

* For the column "Author" I added a way to customize "and" and "et al." in the settings. The default is English.. 
![image](https://github.com/frianasoa/Ze-Notes/assets/5507310/b3baf44d-cb64-4fcc-9a78-a03fa9ee31f8)

* As for the crash, I will fix it when I have time. 
You can try to update your plugin from Zotero without downloading the xpi. You still have to restart Zotero afterwards (I plan to fix this with the crash).
Tools > Add-ons > Ze Notes > "Click the cog" > Check for updates
![image](https://github.com/frianasoa/Ze-Notes/assets/5507310/6df2bdd6-e31c-48de-94b3-593a84e91b44)

**Comment by panyuz** [comment]
Thank you for your work. The plugin is now working very well.
