### ISSUE TITLE
[Request] Add support to show images marked directly with "Select Area" Tool

### ISSUE THREAD

**Issue by Luciatl** [frianasoa/Ze-Notes#15]
Hi, thanks for this incredibly amazing plugin!!   I'm wondering if it is possible to show note image selected using Zotero "Select Area" Tool directly in the table (currently it only shows a `""` instead of the selected image). (I'm using Zotero7 on macos.)

The workflow is shown below:

![image](https://github.com/frianasoa/Ze-Notes/assets/41283692/198793e7-a75a-46b9-b1f7-9290da6fbfaa)

![image](https://github.com/frianasoa/Ze-Notes/assets/41283692/9dda57d5-b97e-4437-8bb6-d44803961a24)

**Comment by Luciatl** [comment]
By the way, I would greatly appreciate it if there could be an option to adjust the font size in the settings. Thank you.

**Comment by frianasoa** [comment]
Thanks for the detailed feedback.
It should work now. The size of the image will be relative the the column width. Resize the column in settings to resize the image. 

You can adjust the font size in the settings.
![image](https://github.com/frianasoa/Ze-Notes/assets/5507310/b049d012-83f6-4a37-9691-03dc8c31d84b)

**Comment by Luciatl** [comment]
It's now working perfectly! 
Thank you so much for your prompt response and this amazing tool!!!
