### ISSUE TITLE
Pressing ctrl only makes the text enlarge when ctrl+c copies the text.

### ISSUE THREAD

**Issue by zzlb0224** [frianasoa/Ze-Notes#17]
Thank you for your continued interest in this project.

Pressing ctrl only makes the text enlarge when ctrl+c copies the text.

The following are suggestions for modifications.

![image](https://github.com/frianasoa/Ze-Notes/assets/8912444/accd2970-bea7-4f86-b3d8-d9d7de90a03d)

**Comment by frianasoa** [comment]
Thanks for your feedback.
I am sorry I was away for a while. 
It should be fixed now.

**Comment by zzlb0224** [comment]
Thank you
