### ISSUE TITLE
open Tab by loadURI get error

### ISSUE THREAD

**Issue by zzlb0224** [frianasoa/Ze-Notes#18]
NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0 [nsIWebNavigation.loadURI]

try this.
change 
```
     Ui.iframe.loadURI(url, {
```

to 
```
      const iframe = Ui.iframe;
      try {
        iframe.loadURI(url, {
          triggeringPrincipal:
            Services.scriptSecurityManager.getSystemPrincipal(),
        });
      } catch (e) {
          ztoolkit.log("loadURI 错误修复了吗？");
        iframe.src = url;
      }
```

**Comment by frianasoa** [comment]
Hi!
Thanks for your feedback. Yes, it does not seem to work with the new update of Zotero 7. 
I will work on it. There are other parts of the code that I need to change as well.

**Comment by hahahacecilia** [comment]
Finally it works with my Zotero 7, thanks a lot!

**Comment by zzlb0224** [comment]
谢谢，我更新一下
