### ISSUE TITLE
ZeNotes does not work with group library

### ISSUE THREAD

**Issue by huyiwen** [frianasoa/Ze-Notes#20]
Hello @frianasoa, thanks for the great work! It really helps to organize all the annotations and notes!!

However, I am encountering some issues when using Ze-Notes with group libraries. Notes do not show up in Ze-Notes when using group libraries.

<img width="1552" alt="image" src="https://github.com/frianasoa/Ze-Notes/assets/5737212/df79631f-855c-4071-bcb1-e6291d7f9e83">

**Comment by frianasoa** [comment]
Thanks for your feedback. 
It has been some time since you have filed the issue. Did you manage to make it work? 
It should work in group libraries. Please check if you have the notes or annotations in the items in the group library. Also please tell me your version of Zotero. Thanks.

**Comment by huyiwen** [comment]
Thank you for replying! I moved the papers to another group library and everything worked all fine.
