### ISSUE TITLE
The Ze-Notes visualization window displays garbled Chinese characters

### ISSUE THREAD

**Issue by HeChao0915** [frianasoa/Ze-Notes#21]
Thank you very much for the Zotero plugin developed.
I noticed that the visualization window often shows garbled Chinese characters, which might be related to the default font settings of the plugin.
May I ask if it is possible to customize the font, or if you could provide a selection of fonts to choose from?

**Comment by frianasoa** [comment]
Thanks for your feedback. 
It has been some time since you have filed the issue. I would appreciate it if you could send a screenshot. Thanks.

**Comment by HeChao0915** [comment]
Thank you for your reply! 
As shown in the red line part of the figure.
The problem is mainly that some text is accidentally bolded, and it's more noticeable if it was bolded in the first plac
![Quicker_20241010_113009](https://github.com/user-attachments/assets/816fb0c2-3c00-4a22-a3f7-51fd862fba10)

**Comment by frianasoa** [comment]
Thank you for the screenshot. 
From version 0.8.7, you can change the font-family in Global settings > Global display. I am not sure if it can solve your problem.
If you need specific fonts, add them to the box on your right and you will be able to select them from the select box on your left. You may need to close and open the setting windows to see the change.

![image](https://github.com/user-attachments/assets/b55e68e7-9a92-4041-9e2a-e00f74143eb0)

**Comment by HeChao0915** [comment]
Great ! Thanks very much. 
When I changed the font, my problem was well solved !
