### ISSUE TITLE
Request support for customizing the OpenAI  Base-API URL address.

### ISSUE THREAD

**Issue by seifer08ms** [frianasoa/Ze-Notes#22]
Currently, the plugin may be limited by its use of a predefined OpenAI API endpoint. However, the ability to set a custom OpenAI API URL would accommodate various user needs, including compliance with specific API access requirements or integration with self-hosted solutions.
Thank you for considering this enhancement. I believe it would make the plugin even more versatile and valuable to its user base.

**Comment by frianasoa** [comment]
Thanks for your feedback. Please check version 0.8.8 and try if it works for you.

**Comment by seifer08ms** [comment]
Awesome !
