### ISSUE TITLE
XLS Export error

### ISSUE THREAD

**Issue by debritto** [frianasoa/Ze-Notes#26]
Hi. I'm trying to export the notes table to xls format, but this error is occurring: 

Uncaught ReferenceError: FileUtils is not defined
    createfiles chrome://ze-notes/content/notes/io.js:141
    export chrome://ze-notes/content/notes/io.js:63
io.js:141:4

The file is not generating.
I'm using Zotero 7.0.7 (64bit) Window version.

**Comment by frianasoa** [comment]
Thanks. 
Should work now in version 0.8.6.

**Comment by debritto** [comment]
Hi @frianasoa !
It's working perfectly now! 
Thank you so much and warm regards from Brazil!

**Comment by debritto** [comment]
Done
