### ISSUE TITLE
Not displaying notes

### ISSUE THREAD

**Issue by jhs1965net** [frianasoa/Ze-Notes#4]
Hi , thanks for the excellent plug in , very useful , 
The only issue is that I can't open the notes with this warning:

notes.init 1: Error: getNotes() cannot be called on items of type 'note'

**Comment by frianasoa** [comment]
Hi!
Sorry for the delay.
Could you tell me which version you are using (This should have been fixed in recent versions)?
Thank you.

**Comment by wuyan0808** [comment]
> Hi , thanks for the excellent plug in , very useful , The only issue is that I can't open the notes with this warning:
> 
> notes.init 1: Error: getNotes() cannot be called on items of type 'note'

Do not display standalone note as a item. You can categorize standalone note into a separate collection folder or move  it under  other item type(articles, books, etc.).
