### ISSUE TITLE
SUPER Wow! And, Some Files Not Working.

### ISSUE THREAD

**Issue by tripluoffthoranlz** [frianasoa/Ze-Notes#6]
Hi,

I got the plugin to work! 💯 Yay!

Here's what I'm seeing.  I tested it using five different PDF files.

Three worked fine - and **WOW!**  That TABLE and what it CAN DO!  **That's the DREAM.  Your work is amazing!!!**

Trouble I'm having is that with two files, the system only loaded the table headers of the existing tages, but left the columns all blank.

So, 3 of 5 PDF files worked perfectly.

The other two - though they HAD annotaions, the table only loads the headers / tag names.  No highlight content / columns.

Trouble for me is, the 5th file is REALLY the main file I need to work with.  And, files like that.

It's original research, so I can't share it.  But, I've uploaded the 4th file, too - it was just an NVIDIA tech guide, but it showed the same problems.

Please can you take a look at the file and see if you can understand what's happening?  I REALLY need Ze-notes to get a BIG project done.  Need your help, please. 

![tags-only-no-highlight-columns](https://github.com/frianasoa/Ze-Notes/assets/148617612/393ba137-1c14-41be-885d-160efce0adb1)
![files-in-cant-see-annotations](https://github.com/frianasoa/Ze-Notes/assets/148617612/c38a70f7-636b-4518-96ac-2b28f1028410)
[nvidia-smi.1.pdf](https://github.com/frianasoa/Ze-Notes/files/13277414/nvidia-smi.1.pdf)

**Comment by frianasoa** [comment]
Hi!

Thanks for using Ze Notes.

Please check the following.

1. Does it work with other collections (folders)? Does it show the table with the contents?
This is how it is normally used: right-click on the collection and open Zenotes from the menu OR Select the collection and open Zenotes from the menu.

2. Do you have annotations in the pdf file? Open the pdf file in Zotero and check. Add annotation and tag and try again if there is no annotations.

3. Do you have tags in your annotations in the pdf? Add tags to annotations for it to show in the table. 

![2023-11-07 175043](https://github.com/frianasoa/Ze-Notes/assets/5507310/d9941cdc-8fbf-4a16-8474-26fbbfbfa0f7)

4. If the table does not show for any collection, close Zotero, head to your Zotero app folder, rename "zenotes.sqlite", restart Zotero and check.
My Zotero folder: C:\Users\My name\Zotero

Best

**Comment by tripluoffthoranlz** [comment]
Hi, Mighty frianasoa!

**Please** let me begin, again, with the HEARTIEST **congratulations**. What you’ve made is **NEXT-LEVEL** – it is actually the ONLY way one could ever keep so many quotes and texts straight in one’s head.  You implementation is nothing short of **MAGIC! :)))**

You wrote:
1.  DOES IT WORK WITH OTHER COLLECTIONS (FOLDERS)? DOES IT SHOW THE TABLE WITH THE CONTENTS? 

Yes.  Works with other collections.  Shows the table with the contents

THIS IS HOW IT IS NORMALLY USED: RIGHT-CLICK ON THE COLLECTION AND OPEN ZENOTES FROM THE MENU OR SELECT THE COLLECTION AND OPEN ZENOTES FROM THE MENU.

Yep, yep.  That’s how I did it.  


2.  DO YOU HAVE ANNOTATIONS IN THE PDF FILE? OPEN THE PDF FILE IN ZOTERO AND CHECK. ADD ANNOTATION AND TAG AND TRY AGAIN IF THERE IS NO ANNOTATIONS.

Yes.  Has annotations.


3.  DO YOU HAVE TAGS IN YOUR ANNOTATIONS IN THE PDF? ADD TAGS TO ANNOTATIONS FOR IT TO SHOW IN THE TABLE.

Yes.  Did have tags, yes.  I made sure.


4.  IF THE TABLE DOES NOT SHOW FOR ANY COLLECTION, CLOSE ZOTERO, HEAD TO YOUR ZOTERO APP FOLDER, RENAME "ZENOTES.SQLITE", RESTART ZOTERO AND CHECK. MY ZOTERO FOLDER: C:\USERS\MY NAME\ZOTERO

This is what’s so curious – the table DOES show for 3 of the 5 PDF files I tested with?

Should I STILL do the re-name?

Also, what happens if you try to add the example PDF I shared – the NVIDIA user guide.  Does Ze Notes work with that file on your side?  (I've attached it here again, too.)

[nvidia-smi.1.pdf](https://github.com/frianasoa/Ze-Notes/files/13278565/nvidia-smi.1.pdf)

Finally!  Is it Ze Notes because, we will have a feeling of **Zen** contentedness having all of one's quotes so well under control? :)))

**Comment by tripluoffthoranlz** [comment]
Which version of 6 do you use?

**Comment by tripluoffthoranlz** [comment]
I mean, on your PC now, what version of the app are you using?

6.0.30?

Or, an older version?

https://zotero.en.uptodown.com/windows

**Comment by frianasoa** [comment]
Hi!

Sorry I am a little busy these days.

I use Zotero 6.0.30.

I have tried the pdf file you provided. There is nothing wrong with the file.
![NVIDIA2023-11-09 224857](https://github.com/frianasoa/Ze-Notes/assets/5507310/89012d4a-3bde-4a94-aa68-0ffe08e62514)
![NVIDIA2023-11-09 224744](https://github.com/frianasoa/Ze-Notes/assets/5507310/ccb7fb2a-22cb-4f23-9850-4e3d825ed71e)

Please check if the file is attached to a bibliography item (not on its own). I tried Book for the type, see below. (You said PDF FILES. This will not work for pdfs floating inside Zotero.)
![NVIDIA2023-11-09 224823](https://github.com/frianasoa/Ze-Notes/assets/5507310/e209f774-2c80-4212-847b-87e9596f9d5d)

Best

**Comment by tripluoffthoranlz** [comment]
Hi frianasoa,

Ah! Yep, yep. Totally understand. :)

I think there may be something wrong with my laptop. Let me try one other thing and I'll post back.

Thanks, again! :D!!

**Comment by tripluoffthoranlz** [comment]
Hi frianasoa,

Ah! Yep, yep. Totally understand. :)

I think there may be something wrong with my laptop. Let me try one other thing and I'll post back.

Thanks, again! :D!!

=•=•=•=•

UPDATE

SuuuuuPER WOW!

Hi, frianasoa!!

Alright! I got it running smoothly it seems in six!

And, I'M TELLING YOU, it's nothing short of AMAZING!!!

PLEASE keep developing it.  Your vision and coding abilities are revolutionary and SUCH a huge HELP.

Thank you, frianasoa!!!
