### ISSUE TITLE
Add Horizontal Rows Based on Table of Contents and Definable

### ISSUE THREAD

**Issue by tripluoffthoranlz** [frianasoa/Ze-Notes#7]
**Hi, frianasoa!**

The plug in is **SOOOOO** useful for literature review.  **THANK YOU** for working so hard to make something so **amazing.**  Right down to a slider for the colors of the highlights.  **GREAT** stuff!

I have an idea.  Tell me what you think.  There's one feature I feel would be a HUGE help.  I'm stuck with reading some really abstract books over the next few years...the arguments are hard for my poor wee brain to follow.

By and large the authors will make their points in each chapter - so that they will present and wrap concept by concept as the chapters go along.

Is there any way we could add horizontal rows to the table?  

My first idea is to inherit the chapter headings in the table of contents.  Since that's already in the file's structure I was thinking that would be less troublesome for you.

That way, there'd be a visible division within the annotations related to each chapter.

_Ideally_, it would be great if we could insert our OWN divisions, as many times in my own reading I'll find that the TOC either omits **lots** of sub headings, or I just get into 10 or 20 paragraphs that define a main idea well.  So, have the TOC as auto-inserted rows, and then have the ability for us to define our own rows if needed.

In using the plug in, I did notice a feature to _add_ a row, but I couldn't figure out how to use it.

With horizontal rows based on the chapter headings inside the table, it would make the reviews of the annotations REALLY easy and increase the efficiency.

How does that sound?

Sincerely,

Trip

**Comment by frianasoa** [comment]
Hi!

In the plugin, "Add row" means add another item to the table. It basically adds a note to the item to make it show in the table. I am sorry but I do not have time to add the option for multiple rows to one item for the moment. 

I usually split my books into chapters and enter them one by one in Zotero, especially when there are different authors for each chapter.

Thanks
