### ISSUE TITLE
Can it be displayed vertically?

### ISSUE THREAD

**Issue by kmxj2020** [frianasoa/Ze-Notes#9]
Can you add vertical browsing?
<img width="363" alt="Snipaste_2023-12-04_12-32-46" src="https://github.com/frianasoa/Ze-Notes/assets/87763851/69261618-4a30-4700-bbc2-4cdb89d0d2a6">

The effect is shown in Fig.

**Comment by frianasoa** [comment]
Hi! 

Thanks for your feedback. That is a good idea indeed. Please check the latest version (update add-on). You can activate "vertical table" in the settings (ZeNotes > Settings > Global settings > Display).

![2023-12-04 193207](https://github.com/frianasoa/Ze-Notes/assets/5507310/c6b388b2-c4a5-461c-a7c4-05fc0fd2f2f2)

Best
